#!/usr/bin/env sh
#   xdg-open-simple xdg-open
#
#   Utility script to open a file or URI in the user's preferred application.
#
#   A fork of the original xdg-open (and xdg-mime) script from the xdg-utils v1.2.1.
#
#   Copyright 2024, Andis Sprinkis <andis@sprinkis.com>
#
#   xdg-open 1.2.1 copyright:
#
#   Copyright 2009-2010, Fathi Boudra <fabo@freedesktop.org>
#   Copyright 2009-2016, Rex Dieter <rdieter@fedoraproject.org>
#   Copyright 2006, Kevin Krammer <kevin.krammer@gmx.at>
#   Copyright 2006, Jeremy White <jwhite@codeweavers.com>
#
#   xdg-mime 1.2.1 copyright:
#
#   Copyright 2009-2010, Fathi Boudra <fabo@freedesktop.org>
#   Copyright 2009-2010, Rex Dieter <rdieter@fedoraproject.org>
#   Copyright 2006, Kevin Krammer <kevin.krammer@gmx.at>
#   Copyright 2006, Jeremy White <jwhite@codeweavers.com>
#
#   LICENSE:
#
#   Permission is hereby granted, free of charge, to any person obtaining a
#   copy of this software and associated documentation files (the "Software"),
#   to deal in the Software without restriction, including without limitation
#   the rights to use, copy, modify, merge, publish, distribute, sublicense,
#   and/or sell copies of the Software, and to permit persons to whom the
#   Software is furnished to do so, subject to the following conditions:
#
#   The above copyright notice and this permission notice shall be included
#   in all copies or substantial portions of the Software.
#
#   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#   THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
#   OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
#   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
#   OTHER DEALINGS IN THE SOFTWARE.

script="$(basename "$0")"

help_info="NAME
    ${script} - opens a file or URI in the registered default application.

SYNOPSIS
    ${script} { file | URI } [-h]

DESCRIPTION
    Utility script to open a file or URI in the registered default application.

    { file | URI }
        The absolute path of the file, or the URI to open.

    -h
        Prints this message.

EXIT CODES
    An exit code of 0 indicates success, while a non-zero exit code indicates failure. The following failure codes can be returned:

    1
        Error in command line syntax.

    2
        One of the files passed on the command line did not exist.

    3
        A required tool could not be found.

    4
        The action failed.

    5
        No permission to read one of the files passed on the command line.

    In case of success the process launched from the .desktop file will not be forked off and therefore may result in xdg-open-generic running for a very long time. This behaviour intentionally differs from most desktop specific openers to allow terminal based applications to run using the same terminal xdg-open was called from.

SEE ALSO
    xdg-open(1), xdg-mime(1), MIME applications associations specification

EXAMPLES
    xdg-open \"http://www.freedesktop.org/\"
        Opens the freedesktop.org website in the user's default browser.

    xdg-open \"/tmp/foobar.png\"
        Opens the PNG image file /tmp/foobar.png in the user's default image viewing application.
"

exit_err_cmd_syntax() { echo "$help_info" 1>&2; exit "1"; }

while getopts :h name; do
  case "$name" in
    "h")
      echo "$help_info"; exit
    ;;
    "?")
      exit_err_cmd_syntax
    ;;
  esac
done

{ [ "$1" = "" ] || [ "$#" -gt "1" ]; } && exit_err_cmd_syntax

url="$1"

# The first_word, last_word functions handle backslashes, but not quote marks.

# shellcheck disable=SC2162
first_word() { read first rest; echo "$first"; }

# shellcheck disable=SC2162
last_word() { read first rest; echo "$rest"; }

# Prefixes a path with a "./" if it starts with a "-".
# This is useful for programs to not confuse paths with options.
unoption_path() {
  case "$1" in
    -*)
      printf "./%s" "$1"
    ;;
    *)
      printf "%s" "$1"
    ;;
  esac
}

# XDG directories
xdg_config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
xdg_config_dirs="${XDG_CONFIG_DIRS:-/etc/xdg}"
xdg_user_dir="${XDG_DATA_HOME:-$HOME/.local/share}"
xdg_system_dirs="${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}"

# Map a .desktop file to a binary
desktop_file_to_binary() {
  desktop="$(basename "$1")"

  IFS_="$IFS" IFS=:
  for dir in $xdg_user_dir $xdg_system_dirs; do
    IFS="$IFS_"

    [ -d "${dir}/applications" ] || [ -d "${dir}/applnk" ] || continue

    file_path=""

    # Check if desktop file contains -
    [ "${desktop#*-}" = "$desktop" ] || {
      vendor="${desktop%-*}" app="${desktop#*-}"

      for fp in "${dir}/applications/${vendor}/${app}" "${dir}/applnk/${vendor}/${app}"; do
        [ -r "$fp" ] && { file_path="$fp"; break; }
      done
    }

    [ "$file_path" ] || {
      for indir in "${dir}/applications/" "${dir}/applications/"*/ "${dir}/applnk/" "${dir}/applnk/"*/; do
        file="${indir}/${desktop}"
        [ -r "$file" ] && { file_path="$file"; break; }
      done
    }

    [ "$file_path" ] && {
      # Remove any arguments (%F, %f, %U, %u, etc.).
      command="$(grep -E "^Exec(\[[^]=]*])?=" "$file_path" | cut -d= -f 2- | first_word)"
      command="$(command -v "$command")"
      readlink -f "$(unoption_path "$command")"
      break
    }
  done
}

# Get INI-format-like file (.desktop, mimeapps.list) value by it's key in a specified [Group]
get_key() {
  file="$1" key="$2" group="$3" first="${4:-0}"

  is_tgt_group="0" result=""
  IFS_="$IFS" IFS=""
  while read -r line; do
    case "$line" in
      "[${group}]")
        is_tgt_group="1"
      ;;
      "["*)
        is_tgt_group="0"
      ;;
      "${key}="*)
        [ "$is_tgt_group" = "0" ] && continue
        result="$(echo "$line" | cut -d= -f 2-)"
        [ "$result" ] && [ "$first" = "1" ] && break
      ;;
    esac
  done < "$file"
  IFS="$IFS_"

  [ "$result" ] && echo "$result"
}

check_mimeapps_list() {
  mime="$1" dir="$2"

  fpath_mimeapps="${dir}/mimeapps.list"

  [ -f "$fpath_mimeapps" ] || return "1"

  result="$(get_key "$fpath_mimeapps" "$mime" "Default Applications" "1")"

  [ "$result" ] || return "1"

  # $result could be a ";" separated list of .desktop files. Uses the first one.
  IFS_="$IFS" IFS=\;
  for app in $result; do
    IFS="$IFS_"
    [ "$(desktop_file_to_binary "$app")" ] && { echo "$app"; return "0"; }
  done

  return "1"
}

defapp() {
  mime="$1"

  case "$mime" in
    */*)
      # Ok
    ;;
    *)
      return "1"
    ;;
  esac

  IFS_="$IFS"

  IFS=:
  for dir in $xdg_config_home $xdg_config_dirs; do
    IFS="$IFS_"
    check_mimeapps_list "$mime" "$dir" && return "0"
  done

  IFS=:
  for dir in $xdg_user_dir $xdg_system_dirs; do
    IFS="$IFS_"
    check_mimeapps_list "$mime" "${dir}/applications" && return "0"
  done

  desktop_file=""

  IFS=:
  for dir in $xdg_user_dir $xdg_system_dirs; do
    IFS="$IFS_"

    desktop_file="$(
      grep "${mime}=" "${dir}/applications/defaults.list" "${dir}/applications/mimeinfo.cache" 2> "/dev/null" | head -n 1 | cut -d '=' -f 2 | cut -d ';' -f 1
    )"

    [ "$desktop_file" ] && { echo "$desktop_file"; break; }
  done
}

# Recursively search .desktop file.
# $1: Application, $2: Directory, $3: Target file, $4: Target URL
search_desktop_file() {
  default="$1" dir="$2" target="$3" target_uri="$4"
  file=""

  # Look for: vendor/app.desktop, vendor-app.desktop
  for fp in "${dir}/${default}" "${dir}/$(echo "$default" | sed -e 's|-|/|')"; do
    [ -r "$fp" ] && { file="$fp"; break; }
  done

  [ "$file" ] && {
    command="$(get_key "$file" "Exec" "Desktop Entry" | first_word)"

    command -v "$command" > "/dev/null" || return

    icon="$(get_key "$file" "Icon" "Desktop Entry")"
    name="$(get_key "$file" "Name" "Desktop Entry")"

    # shellcheck disable=SC2046
    set -- $(get_key "$file" "Exec" "Desktop Entry" | last_word)

    # We need to replace any occurrence of "%f", "%F" and the like by the target file.
    # We examine each argument and append the modified argument to the end then shift.
    args="$#" replaced="0"
    while [ "$args" -gt "0" ]; do
      case $1 in
        %[c])
          replaced="1" arg="$name"
          shift
          set -- "$@" "$arg"
        ;;
        %[fF])
          # If there is only a target_url - return - this application can't handle it.
          [ "$target" ] || return
          replaced="1" arg="$target"
          shift
          set -- "$@" "$arg"
        ;;
        %[uU])
          replaced="1"
          # When an URI is requested use it, otherwise fall back to the filepath.
          arg="${target_uri:-$target}"
          shift
          set -- "$@" "$arg"
        ;;
        %[i])
          replaced="1"
          shift
          set -- "$@" "--icon" "$icon"
        ;;
        *)
          arg="$1"
          shift
          set -- "$@" "$arg"
        ;;
      esac
      args="$((args - 1))"
    done

    [ "$replaced" = "1" ] || set -- "$@" "${target:-$target_uri}"

    env "$command" "$@"; exit "0"
  }

  for d in "${dir}/"*/; do
    [ -d "$d" ] && search_desktop_file "$default" "$d" "$target" "$target_uri"
  done
}

is_file_url="0" has_url_scheme="0" file="" scheme="" mime="" default=""

echo "$url" | grep -q '^file://' && is_file_url="1"
echo "$url" | LC_ALL="C" grep -Eq '^[[:alpha:]][[:alpha:][:digit:]+\.\-]*:' && has_url_scheme="1"

if [ "$is_file_url" = "1" ] || [ "$has_url_scheme" = "0" ]; then
  file="$url" 

  # Convert file URL to a percent-decoded path.
  [ "$is_file_url" = "1" ] && {
    file="${file#file://localhost}"
    file="${file#file://"$(uname -n)"}"
    file="${file#file://}"

    [ "$file" ] && {
      file="${file%%#*}"
      file="${file%%\?*}"
      file="$(echo "$file" | sed -e 's@%\([a-f0-9A-F]\{2\}\)@\\x\1@g')"
      file="$(printf "$file")"
    }
  }

  file="$(readlink -f "$(unoption_path "$file")")"

  [ -e "$file" ] || exit "2"
  [ -r "$file" ] || exit "5"

  mime="$(file --brief --dereference --mime-type "$file" 2> "/dev/null" | sed "s/;.*//")"
else
  scheme="$(echo "$url" | LC_ALL="C" sed -n 's/\(^[[:alpha:]][[:alnum:]+\.-]*\):.*$/\1/p')"
  mime="${scheme:+"x-scheme-handler/${scheme}"}"
fi

default="${mime:+$(defapp "$mime")}"

[ "$default" ] && {
  IFS_="$IFS" IFS=:
  for dir in $xdg_user_dir $xdg_system_dirs; do
    IFS="$IFS_"
    search_desktop_file "$default" "${dir}/applications/" "$file" "${scheme:+$url}"
  done
}

exit "3"
